// client/src/components/site/SiteHeader.tsx
import { useEffect, useRef, useState, type KeyboardEvent } from "react";
import { ChevronDown, Menu, X } from "lucide-react";
import { Link, useLocation } from "wouter";
import { LANGUAGE_LINKS, SITE_NAVIGATION } from "@/site/siteConfig";
import { MobileContactBar, PrimaryContactActions } from "./ContactActions";

export function SiteHeader() {
  const [location] = useLocation();
  const [menuOpen, setMenuOpen] = useState(false);
  const [estateMenuOpen, setEstateMenuOpen] = useState(false);
  const headerRef = useRef<HTMLElement>(null);
  const menuButtonRef = useRef<HTMLButtonElement>(null);
  const navigationRef = useRef<HTMLElement>(null);
  const estateItemRef = useRef<HTMLDivElement>(null);
  const estateToggleRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    setMenuOpen(false);
    setEstateMenuOpen(false);
  }, [location]);

  useEffect(() => {
    if (!menuOpen) return;

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const firstNavigationLink =
      navigationRef.current?.querySelector<HTMLElement>("a, button");
    firstNavigationLink?.focus();

    return () => {
      document.body.style.overflow = previousOverflow;
    };
  }, [menuOpen]);

  useEffect(() => {
    const handlePointerDown = (event: PointerEvent) => {
      if (
        estateMenuOpen &&
        !estateItemRef.current?.contains(event.target as Node)
      ) {
        setEstateMenuOpen(false);
      }
    };

    const handleEscape = (event: globalThis.KeyboardEvent) => {
      if (event.key !== "Escape") return;

      if (menuOpen) {
        setMenuOpen(false);
        setEstateMenuOpen(false);
        menuButtonRef.current?.focus();
        return;
      }

      if (estateMenuOpen) {
        setEstateMenuOpen(false);
        estateToggleRef.current?.focus();
      }
    };

    document.addEventListener("pointerdown", handlePointerDown);
    document.addEventListener("keydown", handleEscape);
    return () => {
      document.removeEventListener("pointerdown", handlePointerDown);
      document.removeEventListener("keydown", handleEscape);
    };
  }, [estateMenuOpen, menuOpen]);

  const closeMobileMenu = (restoreFocus = true) => {
    setMenuOpen(false);
    if (restoreFocus) {
      requestAnimationFrame(() => menuButtonRef.current?.focus());
    }
  };

  const handleHeaderKeyDown = (event: KeyboardEvent<HTMLElement>) => {
    if (!menuOpen || event.key !== "Tab" || !headerRef.current) return;

    const focusable = Array.from(
      headerRef.current.querySelectorAll<HTMLElement>(
        "a[href], button:not([disabled])"
      )
    ).filter(element => element.getClientRects().length > 0);

    const first = focusable[0];
    const last = focusable[focusable.length - 1];
    if (!first || !last) return;

    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  };

  const estateItem = SITE_NAVIGATION[0];

  return (
    <>
      <a className="skip-link" href="#main-content">
        Skip to main content
      </a>
      <div className="desktop-rail" aria-hidden="true">
        <span className="rail-mark">BM</span>
        <span className="rail-line" />
        <span className="rail-label">Brian Miranda Law</span>
      </div>
      <header
        className="site-header"
        ref={headerRef}
        onKeyDown={handleHeaderKeyDown}
      >
        <Link className="brand-lockup" href="/" aria-label="Miranda Law home">
          <img
            className="brand-logo"
            src="/miranda-law-gold.png"
            alt="Miranda Law, Attorneys at Law"
            width="2434"
            height="2401"
          />
        </Link>

        <button
          ref={menuButtonRef}
          className="menu-button"
          type="button"
          aria-label={menuOpen ? "Close menu" : "Open menu"}
          aria-controls="main-navigation"
          aria-expanded={menuOpen}
          onClick={() => {
            if (menuOpen) closeMobileMenu();
            else setMenuOpen(true);
          }}
        >
          {menuOpen ? (
            <X size={24} aria-hidden="true" />
          ) : (
            <Menu size={24} aria-hidden="true" />
          )}
        </button>

        <nav
          ref={navigationRef}
          id="main-navigation"
          className={menuOpen ? "main-nav is-open" : "main-nav"}
          aria-label="Main navigation"
        >
          <div
            ref={estateItemRef}
            className="nav-item-with-menu"
            onPointerEnter={() => setEstateMenuOpen(true)}
            onPointerLeave={() => setEstateMenuOpen(false)}
            onFocusCapture={() => setEstateMenuOpen(true)}
            onBlurCapture={event => {
              if (!event.currentTarget.contains(event.relatedTarget)) {
                setEstateMenuOpen(false);
              }
            }}
          >
            <div className="nav-parent-row">
              <Link
                className={
                  location.startsWith(estateItem.href) ? "is-active" : ""
                }
                href={estateItem.href}
                aria-current={location === estateItem.href ? "page" : undefined}
              >
                {estateItem.label}
              </Link>
              <button
                ref={estateToggleRef}
                className="nav-submenu-toggle"
                type="button"
                aria-label="Toggle Estate Planning pages"
                aria-expanded={estateMenuOpen}
                aria-controls="estate-planning-submenu"
                onClick={event => {
                  if (event.detail > 0) setEstateMenuOpen(true);
                  else setEstateMenuOpen(current => !current);
                }}
              >
                <ChevronDown size={16} aria-hidden="true" />
              </button>
            </div>
            <div
              id="estate-planning-submenu"
              className={estateMenuOpen ? "nav-submenu is-open" : "nav-submenu"}
            >
              {estateItem.children?.map(item => (
                <Link
                  key={item.href}
                  href={item.href}
                  aria-current={location === item.href ? "page" : undefined}
                >
                  {item.label}
                </Link>
              ))}
            </div>
          </div>

          {SITE_NAVIGATION.slice(1).map(item => (
            <Link
              key={item.href}
              className={location === item.href ? "is-active" : ""}
              href={item.href}
              aria-current={location === item.href ? "page" : undefined}
            >
              {item.label}
            </Link>
          ))}

          <div className="nav-languages" aria-label="Questionnaire previews">
            {LANGUAGE_LINKS.map(item => (
              <Link
                key={item.href}
                href={item.href}
                aria-label={`Open the ${item.language} questionnaire preview`}
                aria-current={location === item.href ? "page" : undefined}
              >
                <span className="language-short" aria-hidden="true">
                  {item.label}
                </span>
                <span className="language-full">{item.language}</span>
              </Link>
            ))}
          </div>

          <PrimaryContactActions className="nav-contact-actions" compact />
        </nav>

        {menuOpen ? (
          <button
            className="nav-backdrop"
            type="button"
            aria-label="Close navigation menu"
            tabIndex={-1}
            onClick={() => closeMobileMenu()}
          />
        ) : null}
      </header>
      <MobileContactBar />
    </>
  );
}

// app/components/SiteHeader.vue
<script setup lang="ts">
import { ChevronDown, Menu, X } from "@lucide/vue";

const route = useRoute();
const siteCopy = await useSiteCopy();
const navigation = computed(() => siteCopy.value.site.navigation.primary);
const languageLinks = computed(() => siteCopy.value.site.navigation.languages);
const copy = computed(() => siteCopy.value.site.header);
const menuOpen = ref(false);
const estateMenuOpen = ref(false);
const menuButton = ref<HTMLButtonElement>();
const header = ref<HTMLElement>();

const estateItem = computed(() => navigation.value[0]!);

function closeMobileMenu(restoreFocus = false) {
  menuOpen.value = false;
  estateMenuOpen.value = false;

  if (restoreFocus) {
    requestAnimationFrame(() => menuButton.value?.focus());
  }
}

function handleEscape(event: KeyboardEvent) {
  if (event.key !== "Escape") return;

  if (menuOpen.value) {
    closeMobileMenu(true);
  } else if (estateMenuOpen.value) {
    estateMenuOpen.value = false;
  }
}

function trapMenuFocus(event: KeyboardEvent) {
  if (!menuOpen.value || event.key !== "Tab" || !header.value) return;

  const focusable = Array.from(
    header.value.querySelectorAll<HTMLElement>(
      "a[href], button:not([disabled])"
    )
  ).filter(element => element.getClientRects().length > 0);
  const first = focusable[0];
  const last = focusable.at(-1);

  if (!first || !last) return;
  if (event.shiftKey && document.activeElement === first) {
    event.preventDefault();
    last.focus();
  } else if (!event.shiftKey && document.activeElement === last) {
    event.preventDefault();
    first.focus();
  }
}

watch(
  () => route.fullPath,
  () => closeMobileMenu()
);

watch(menuOpen, isOpen => {
  if (!import.meta.client) return;
  document.body.style.overflow = isOpen ? "hidden" : "";
});

onMounted(() => document.addEventListener("keydown", handleEscape));
onBeforeUnmount(() => {
  document.removeEventListener("keydown", handleEscape);
  document.body.style.overflow = "";
});
</script>

<template>
  <a class="skip-link" href="#main-content">{{ copy.skipLink }}</a>
  <div class="desktop-rail" aria-hidden="true">
    <span class="rail-mark">{{ copy.railMark }}</span>
    <span class="rail-line" />
    <span class="rail-label">{{ copy.railLabel }}</span>
  </div>
  <header ref="header" class="site-header" @keydown="trapMenuFocus">
    <NuxtLink class="brand-lockup" to="/" :aria-label="copy.homeAriaLabel">
      <NuxtImg
        class="brand-logo"
        src="/miranda-law-gold.png"
        :alt="copy.logoAlt"
        width="2434"
        height="2401"
        densities="1x"
      />
    </NuxtLink>

    <button
      ref="menuButton"
      class="menu-button"
      type="button"
      :aria-label="menuOpen ? copy.closeMenuAriaLabel : copy.openMenuAriaLabel"
      aria-controls="main-navigation"
      :aria-expanded="menuOpen"
      @click="menuOpen ? closeMobileMenu(true) : (menuOpen = true)"
    >
      <X v-if="menuOpen" :size="24" aria-hidden="true" />
      <Menu v-else :size="24" aria-hidden="true" />
    </button>

    <nav
      id="main-navigation"
      class="main-nav"
      :class="{ 'is-open': menuOpen }"
      :aria-label="copy.navigationAriaLabel"
    >
      <div
        class="nav-item-with-menu"
        @mouseenter="estateMenuOpen = true"
        @mouseleave="estateMenuOpen = false"
        @focusin="estateMenuOpen = true"
        @focusout="
          event => {
            const target = event.currentTarget as HTMLElement;
            if (!target.contains(event.relatedTarget as Node | null))
              estateMenuOpen = false;
          }
        "
      >
        <div class="nav-parent-row">
          <NuxtLink
            :class="{ 'is-active': route.path.startsWith(estateItem.href) }"
            :to="estateItem.href"
            :aria-current="route.path === estateItem.href ? 'page' : undefined"
          >
            {{ estateItem.label }}
          </NuxtLink>
          <button
            class="nav-submenu-toggle"
            type="button"
            :aria-label="copy.estateMenuAriaLabel"
            :aria-expanded="estateMenuOpen"
            aria-controls="estate-planning-submenu"
            @click="estateMenuOpen = !estateMenuOpen"
          >
            <ChevronDown :size="16" aria-hidden="true" />
          </button>
        </div>
        <div
          id="estate-planning-submenu"
          class="nav-submenu"
          :class="{ 'is-open': estateMenuOpen }"
        >
          <NuxtLink
            v-for="item in estateItem.children"
            :key="item.href"
            :to="item.href"
            :aria-current="route.path === item.href ? 'page' : undefined"
          >
            {{ item.label }}
          </NuxtLink>
        </div>
      </div>

      <NuxtLink
        v-for="item in navigation.slice(1)"
        :key="item.href"
        :class="{ 'is-active': route.path === item.href }"
        :to="item.href"
        :aria-current="route.path === item.href ? 'page' : undefined"
      >
        {{ item.label }}
      </NuxtLink>

      <div class="nav-languages" :aria-label="copy.questionnairesAriaLabel">
        <NuxtLink
          v-for="item in languageLinks"
          :key="item.href"
          :to="item.href"
          :aria-label="
            copy.questionnaireLinkAriaLabel.replace('{language}', item.language)
          "
          :aria-current="route.path === item.href ? 'page' : undefined"
        >
          <span class="language-short" aria-hidden="true">{{
            item.label
          }}</span>
          <span class="language-full">{{ item.language }}</span>
        </NuxtLink>
      </div>

      <ContactActions class="nav-contact-actions" compact />
    </nav>

    <button
      v-if="menuOpen"
      class="nav-backdrop"
      type="button"
      :aria-label="copy.backdropAriaLabel"
      tabindex="-1"
      @click="closeMobileMenu(true)"
    />
  </header>
  <aside class="mobile-contact-bar" :aria-label="copy.quickContactAriaLabel">
    <ContactActions compact />
  </aside>
</template>
