// client/src/components/site/SiteFooter.tsx
import { Link } from "wouter";
import {
  CONTACT,
  ESTATE_PLANNING_NAVIGATION,
  LANGUAGE_LINKS,
  RESOURCE_NAVIGATION,
  getPhoneHref,
} from "@/site/siteConfig";

export function SiteFooter() {
  return (
    <footer className="site-footer site-footer-expanded">
      <div className="footer-brand-column">
        <Link className="footer-logo-link" href="/">
          <img
            className="footer-logo"
            src="/miranda-law-gold.png"
            alt="Miranda Law, Attorneys at Law"
            width="2434"
            height="2401"
            loading="lazy"
            decoding="async"
          />
        </Link>
        <p>
          Clear estate-planning guidance for North Jersey families, available in
          English, Spanish, and Portuguese.
        </p>
      </div>

      <div className="footer-link-column">
        <h2>Estate planning</h2>
        {ESTATE_PLANNING_NAVIGATION.map(item => (
          <Link key={item.href} href={item.href}>
            {item.label}
          </Link>
        ))}
      </div>

      <div className="footer-link-column">
        <h2>Resources</h2>
        {RESOURCE_NAVIGATION.map(item => (
          <Link key={item.href} href={item.href}>
            {item.label}
          </Link>
        ))}
        <Link href="/about">About Brian</Link>
        <Link href="/other-services">Other legal services</Link>
      </div>

      <div className="footer-contact-column">
        <h2>Start a conversation</h2>
        <a href={getPhoneHref()}>{CONTACT.phoneDisplay}</a>
        <a href={`mailto:${CONTACT.email}`}>{CONTACT.email}</a>
        <a href={CONTACT.mapUrl} target="_blank" rel="noreferrer">
          {CONTACT.addressLines[0]}
          <br />
          {CONTACT.addressLines[1]}
        </a>
        <div className="footer-language-links">
          {LANGUAGE_LINKS.map(item => (
            <Link key={item.href} href={item.href}>
              {item.language}
            </Link>
          ))}
        </div>
      </div>

      <div className="footer-legal-row">
        <span>© 2026 {CONTACT.name}</span>
        <Link href="/privacy">Privacy</Link>
        <Link href="/cookies">Cookies</Link>
        <Link href="/disclaimer">Website disclaimer</Link>
        <Link href="/accessibility">Accessibility</Link>
        <span>
          Attorney advertising. Prior results do not guarantee a similar
          outcome.
        </span>
      </div>
    </footer>
  );
}

// app/components/SiteFooter.vue
<script setup lang="ts">
import { getPhoneHref } from "~/data/routes";
import { blogPosts } from "#site-content";

const siteCopy = useSiteCopy();
const site = computed(() => siteCopy.value.site);
const copy = computed(() => site.value.footer);
const contact = computed(() => site.value.contact);
const currentYear = new Date().getFullYear();
const resourceLinks = computed(() => [
  ...site.value.navigation.resources,
  ...(blogPosts.length
    ? [{ label: siteCopy.value.blog.label, href: siteCopy.value.blog.path }]
    : []),
]);
</script>

<template>
  <footer class="site-footer site-footer-expanded">
    <div class="footer-brand-column">
      <NuxtLink class="footer-logo-link" to="/">
        <NuxtImg
          class="footer-logo"
          src="/miranda-law-gold.png"
          :alt="site.header.logoAlt"
          width="2434"
          height="2401"
          loading="lazy"
          densities="1x"
        />
      </NuxtLink>
      <p>{{ copy.description }}</p>
    </div>

    <div class="footer-link-column">
      <h2>{{ copy.estatePlanningHeading }}</h2>
      <NuxtLink
        v-for="item in site.navigation.estatePlanning"
        :key="item.href"
        :to="item.href"
      >
        {{ item.label }}
      </NuxtLink>
    </div>

    <div class="footer-link-column">
      <h2>{{ copy.resourcesHeading }}</h2>
      <NuxtLink v-for="item in resourceLinks" :key="item.href" :to="item.href">
        {{ item.label }}
      </NuxtLink>
      <NuxtLink to="/about">{{ copy.aboutLabel }}</NuxtLink>
      <NuxtLink to="/other-services">{{ copy.otherServicesLabel }}</NuxtLink>
    </div>

    <div class="footer-contact-column">
      <h2>{{ copy.contactHeading }}</h2>
      <a :href="getPhoneHref(contact.phoneHref)">{{ contact.phoneDisplay }}</a>
      <a :href="`mailto:${contact.email}`">{{ contact.email }}</a>
      <a :href="contact.mapUrl" target="_blank" rel="noreferrer">
        {{ contact.addressLines[0] }}<br />
        {{ contact.addressLines[1] }}
      </a>
      <div class="footer-language-links">
        <NuxtLink
          v-for="item in site.navigation.languages"
          :key="item.href"
          :to="item.href"
        >
          {{ item.language }}
        </NuxtLink>
      </div>
    </div>

    <div class="footer-legal-row">
      <span>© {{ currentYear }} {{ contact.name }}</span>
      <NuxtLink to="/privacy">{{ copy.privacyLabel }}</NuxtLink>
      <NuxtLink to="/cookies">{{ copy.cookiesLabel }}</NuxtLink>
      <NuxtLink to="/disclaimer">{{ copy.disclaimerLabel }}</NuxtLink>
      <NuxtLink to="/accessibility">{{ copy.accessibilityLabel }}</NuxtLink>
      <span>{{ copy.attorneyAdvertising }}</span>
    </div>
  </footer>
</template>
